export const SET_CUSTOMER = 'SET_CUSTOMER'
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
export const TOGGLE_CUSTOMER_MODAL = 'TOGGLE_CUSTOMER_MODAL'
export const CLEAN_CUSTOMER_INFO = 'CLEAN_CUSTOMER_INFO'
